apiVersion: apps/v1
kind: Deployment
metadata:
  name: sports-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sports-backend
  template:
    metadata:
      labels:
        app: sports-backend
    spec:
      containers:
        - name: backend
          image: himanshi1409/sports-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URL
              value: "mongodb://sports-mongo:27017/sportsdb"
---
apiVersion: v1
kind: Service
metadata:
  name: sports-backend
spec:
  selector:
    app: sports-backend
  ports:
    - port: 5000
      targetPort: 5000
  type: NodePort